name: My first Github action file

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo files
              uses: actions/checkout@v4
            - name: Welcome Message
              run: |
               echo "Hello from github actions!!!"
               ls -ltra
               cat README.md