name: My first Github action file

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Hello from github actions!!!"
            - name: List files
              run: ls
            - name: Read files
              run: cat README.md